### PR TITLE
Journal Week 2 Revisions

### PR DESCRIPTION
**Pull request by ShayHall**
* [x] **Journal, Week 2**
  * [x] Final Draft, First Revision
  * [x] Peer reviewed by 2 people
  * [x] Final Draft, 2nd Revision
  * [x] Peer reviewed by 2 people
  * [x] 2x :+1:s

### CODE REVIEW

**Comment by nickycadavillo** [comment]
:+1: Shay, this is GOLD STAR material. :star:   Not only have you written a thorough and comprehensive entry about the technical stuff, but you've included lots of great references and ended it with a solid conclusion.   Also, thanks for the lesson in Agile Software Development! Also liked the markdown in it!

**Comment by Ricecoder** [comment]
:+1: WOW! That is a top-notch journal entry! Very informative and entertaining. Good job!

**Comment by jeffworley** [comment]
Excellent level of detail and recall Shay!  I don't see anything that jumps out at me as a need for revision or that needs to be expounded upon.  :+1:

**Comment by s4dmw** [comment]
Good work. The content looks great.

Check the formatting on that "Encapsulation" link so that it looks like the others.

:+1:

**Comment by Ricecoder** [comment]
If you are a smurf then you are smurfing better and better! Keep up the good work! :+1:

**Comment by rosalsm** [comment]
You will smurf!!! I like how we are getting more and more personal on our journal :+1:

**Pull request merged**
